### ISSUE TITLE
Stops Writing Headers 

### ISSUE THREAD

**Issue by miketheknight2016** [EPPlusSoftware/EPPlus#290] opened 2021-01-30 00:46 UTC
Using version 5.5.2 I can only write 34 headers to an .xlsx using Office 2016.  Anything after 34 the code iterates the line but no data is actually written to the Excel file.  I downgraded my version to 4.0.5 and the issue does not exist.  No data was written in AF1 to the end.  

If it matters Windows 10, Visual Studio 2019

This is the code I used:
    using (ExcelPackage pck = new ExcelPackage())
    {
        ExcelWorksheet ws = pck.Workbook.Worksheets.Add(customer);
        ws.Cells["A1"].Value = "First Name";
        ws.Cells["B1"].Value = "Last Name";
        ws.Cells["C1"].Value = "Address1";
        ws.Cells["D1"].Value = "Address2";
        ws.Cells["E1"].Value = "City";
        ws.Cells["F1"].Value = "State";
        ws.Cells["G1"].Value = "Zip";
        ws.Cells["H1"].Value = "Phone";
    
        //keep writing data to I, J, K, L, etc
    
        ws.Cells["AF1"].Value = "Hire Date";
        ws.Cells["AG1"].Value = "Manager Name";
        ws.Cells["AH1"].Value = "Manager Hire Date";
        ws.Cells["AI1"].Value = "Simlcam Number";

        FileInfo fi = new FileInfo("C:\\Test\\EPPlusWorkbook.xlsx");
        await pck.SaveAsAsync(fi);
    }

**Comment by JanKallman** [comment] 2021-02-01 07:48
I tried to reproduce this, but it works for all I can see...
```C#
            using (ExcelPackage pck = new ExcelPackage())
            {
                ExcelWorksheet ws = pck.Workbook.Worksheets.Add("customer");
                ws.Cells["A1"].Value = "First Name";
                ws.Cells["B1"].Value = "Last Name";
                ws.Cells["C1"].Value = "Address1";
                ws.Cells["D1"].Value = "Address2";
                ws.Cells["E1"].Value = "City";
                ws.Cells["F1"].Value = "State";
                ws.Cells["G1"].Value = "Zip";
                ws.Cells["H1"].Value = "Phone";

                for(int col=9;col<32;col++)
                {
                    ws.Cells[ExcelCellBase.GetAddress(1,col)].Value = ExcelCellBase.GetAddress(1, col);
                }

                //keep writing data to I, J, K, L, etc

                ws.Cells["AF1"].Value = "Hire Date";
                ws.Cells["AG1"].Value = "Manager Name";
                ws.Cells["AH1"].Value = "Manager Hire Date";
                ws.Cells["AI1"].Value = "Simlcam Number";

                FileInfo fi = new FileInfo("C:\\Test\\EPPlusWorkbook.xlsx");
                await pck.SaveAsAsync(fi);
            }
```
Can you provide some code that reproduces this issue?

**Comment by miketheknight2016** [comment] 2021-02-01 18:45
This is full code I used to produce this issue
`	public static void WriteHeaders(ExcelWorksheet ws)
	{           
		ws.Cells["A1"].Value = "First Name";
		ws.Cells["B1"].Value = "Last Name";
		ws.Cells["C1"].Value = "Address1";
		ws.Cells["D1"].Value = "Address2";
		ws.Cells["E1"].Value = "City";
		ws.Cells["F1"].Value = "State";
		ws.Cells["G1"].Value = "Zip";
		ws.Cells["H1"].Value = "Phone";
		ws.Cells["I1"].Value = "Prev Job 1";
		ws.Cells["J1"].Value = "Prev Job 1 Address";
		ws.Cells["K1"].Value = "Prev Job 1 Phone";
		ws.Cells["L1"].Value = "Prev Job 2";
		ws.Cells["M1"].Value = "Prev Job 2 Address";
		ws.Cells["N1"].Value = "Prev Job 2 Phone";
		ws.Cells["O1"].Value = "Prev Job 3";
		ws.Cells["P1"].Value = "Prev Job 3 Address";
		ws.Cells["Q1"].Value = "Prev Job 3 Phone";
		ws.Cells["R1"].Value = "Prev Job 1 Manager Name";
		ws.Cells["S1"].Value = "Prev Job 1 Manager Phone";
		ws.Cells["T1"].Value = "Prev Job 2 Manager Name";
		ws.Cells["U1"].Value = "Prev Job 2 Manager Phone";
		ws.Cells["V1"].Value = "Prev Job 3 Manager Name";
		ws.Cells["W1"].Value = "Prev Job 3 Manager Phone";
		ws.Cells["X1"].Value = "Contact Job 1";
		ws.Cells["Y1"].Value = "Contact Job 2";
		ws.Cells["Z1"].Value = "Contact Job 3";
		ws.Cells["AA1"].Value = "Job 1 Salary";
		ws.Cells["AB1"].Value = "Job 2 Salary";
		ws.Cells["AC1"].Value = "Job 3 Salary";
		ws.Cells["AD1"].Value = "Job 1 Hire Date";
		ws.Cells["AE1"].Value = "Job 2 Hire Date";
		ws.Cells["AF1"].Value = "Job 3 Hire Date";
		ws.Cells["AG1"].Value = "Manager Name";
		ws.Cells["AH1"].Value = "Manager Hire Date";
		ws.Cells["AI1"].Value = "Simlcam Number";
		ws.Cells["A1:AJ1"].Style.Font.Bold = true;
	}	


	public static async Task WriteResultsToExcel(string emp)
	{
		using (ExcelPackage pck = new ExcelPackage())
		{
			ExcelWorksheet ws = pck.Workbook.Worksheets.Add(employee);

			WriteHeaders(ws);
		}
	}`

**Comment by chriswaadt** [comment] 2021-02-17 23:11
I just was curious about the code. For me all headers are shown in the Excel file (opened in Excel 2016).

**Comment by JanKallman** [comment] 2021-02-18 07:09
Yes, that code works fine for me as well. If you still have this problem, please also provide your environment, culture and any other setting that could matter.

**Comment by miketheknight2016** [comment] 2021-02-18 19:03
@JanKallman & @chriswaadt - full code from Microsoft Visual Studio Community 2019 Version 16.8.4 created a Console App in .NET Core 3.1.  using EPPlus (5.5.2).  Windows 10 Environment

```
using OfficeOpenXml;
using System;
using System.IO;
using System.Threading.Tasks;

namespace TestEPP
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            await WriteResultsToExcel();
        }

        public static async Task WriteResultsToExcel()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (ExcelPackage pck = new ExcelPackage())
            {
                ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Test");

                await WriteHeaders(ws);

                DateTime dt = DateTime.Now;

                FileInfo fi = new FileInfo("C:\\Test\\Test_" + dt.ToString("MMM") + ".xlsx");
                pck.SaveAs(fi);
            }
        }

        public static async Task WriteHeaders(ExcelWorksheet ws)
        {
            ws.Cells["A1"].Value = "Date Order Placed";
            ws.Cells["B1"].Value = "Time Order Placed";
            ws.Cells["C1"].Value = "Date Shipment";
            ws.Cells["D1"].Value = "Turnaround Days";
            ws.Cells["E1"].Value = "Order Number";
            ws.Cells["F1"].Value = "Payment Method";
            ws.Cells["G1"].Value = "PO Number";
            ws.Cells["H1"].Value = "Acct Accounting Unit";
            ws.Cells["I1"].Value = "Order Line #";
            ws.Cells["J1"].Value = "Product SKU";
            ws.Cells["K1"].Value = "Kit SKU";
            ws.Cells["L1"].Value = "Product Name";
            ws.Cells["M1"].Value = "Item Type";
            ws.Cells["N1"].Value = "Customer Owned";
            ws.Cells["O1"].Value = "Qty Ordered";
            ws.Cells["P1"].Value = "Qty Shipped";
            ws.Cells["Q1"].Value = "Revenue Cost (Wholesale Price)";
            ws.Cells["R1"].Value = "Price Each";
            ws.Cells["S1"].Value = "Price Extended";
            ws.Cells["T1"].Value = "Sales Tax (8%)";
            ws.Cells["U1"].Value = "Shipping Cost";
            ws.Cells["V1"].Value = "Total Price";
            ws.Cells["W1"].Value = "Total Orders w/ a Promo Item";
            ws.Cells["X1"].Value = "Total Promo Line Items";
            ws.Cells["Y1"].Value = "CC Charge";
            ws.Cells["Z1"].Value = "CC Collected (Y/N)";
            ws.Cells["AA1"].Value = "Amount Authorized";
            ws.Cells["AB1"].Value = "Amount Collected";
            ws.Cells["AC1"].Value = "Ordered By";
            ws.Cells["AD1"].Value = "Ship To Name";
            ws.Cells["AE1"].Value = "Ship To Address";
            ws.Cells["EF1"].Value = "Ship To City";
            ws.Cells["AG1"].Value = "Ship To State";
            ws.Cells["AH1"].Value = "Ship Method";
            ws.Cells["AI1"].Value = "Ship Account";
            ws.Cells["A1:AJ1"].Style.Font.Bold = true;
        }
    }
}
```

**Comment by chriswaadt** [comment] 2021-02-19 22:03
Works for me.

**Comment by JanKallman** [comment] 2021-02-24 07:09
Works as intended for me.
You are however referencing EF1 here instead of AF1?...
`ws.Cells["EF1"].Value = "Ship To City";`
I will close this one. Please reopen if you still have the issue with a reproducable sample.

**Closed by JanKallman** 2021-02-24 07:09 UTC
