### ISSUE TITLE
v6 Copying a sheet with a Picture which is grouped results in corrupted document

### ISSUE THREAD

**Issue by dbronson4672** [EPPlusSoftware/EPPlus#1143] opened 2023-11-04 16:56 UTC
If you use the Worksheets.Copy Method or Worksheets.Add Method w/Copy
And the sheet contains a picture which is inside a group, it results in a corrupted excel document
If you ungroup the picture it seems to work fine.

Testing with version 6.2.10 net35 libraries

While I haven't tried man shape times, it seems to be limited to pictures.   Grouped shapes such as ovals, rectangles  seem to be fine

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error021360_01.xml</logFileName><summary>Errors were detected in file 'C:\templates\Skills.target.xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Drawing from /xl/drawings/drawing4.xml part (Drawing shape)</repairedRecord></repairedRecords></recoveryLog>

**Comment by OssianEPPlus** [comment] 2023-11-06 06:51
Thanks for letting us know! We'll look into it and get back to you shortly.

**Comment by OssianEPPlus** [comment] 2023-11-06 07:24
I seem unable to reproduce your error _exactly_ . There's definitely some kind of bug as when I open Excel after copying there's an error message of "This picture can't be displayed." On all copied sheets but the workbook is not corrupt on our side.

Could you provide a reproducible code-sample and/or a corrupted workbook? Are you creating and copying images and sheets from scratch in the same run or are you reading in a sheet that already has a grouped image and then copying it?

**Comment by dbronson4672** [comment] 2023-11-06 18:18
What version of Excel are you using to open the document, I was using Excel 2007 (yes I know very old).    I will try a few newer versions to see if behaves the same way and update the issue

**Comment by dbronson4672** [comment] 2023-11-06 21:47
Ok, I just confirmed that later versions of Excel do **not**  produce the error message.
Only the image as you mention is not displayed correctly.
It behaves the same way as you described.

Only Excel 2007 produced the following error when opening the document.
![ErrorMessage](https://github.com/EPPlusSoftware/EPPlus/assets/28630767/114f50e8-d045-41e7-8629-566daa1e2594)

**Comment by OssianEPPlus** [comment] 2023-11-07 07:32
Ah alright that makes sense! We've located the issue and are in the process of working on a bugfix. I did manage to force the error message even in new version by manually editing the file when I was trying to ascertain why this was happening.

**Comment by JanKallman** [comment] 2023-11-10 06:56
Fixed in 6.2.12 and 7.0.1

**Closed as completed by JanKallman** 2023-11-10 06:56 UTC
