### ISSUE TITLE
auto-filters ON - Worksheets method fails

### ISSUE THREAD

**Issue by ivor52** [EPPlusSoftware/EPPlus#76] opened 2020-04-07 10:26 UTC
When having auto-filter ON on one or more columns of data, the method ```ExcelPackage.Workbook.Worksheets``` fails with the following message:

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
```

by executing the following code snippet on the attached input file
`  
using (ExcelPackage p = new ExcelPackage(eF))  
{  
    ExcelWorksheet ws = p.Workbook.Worksheets[1];  
}   
`

remove the auto-filter from the columns and the call succeeds.

**Comment by ivor52** [comment] 2020-04-07 10:29
[auot-filter.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4443572/auot-filter.xlsx)

**Comment by JanKallman** [comment] 2020-04-08 08:44
This works when I try it. Which version are you using?

**Comment by JanKallman** [comment] 2020-04-27 07:12
I'll Close this issue as I can't reproduce the problem. Feel free to reopen it and supply a reproducible case.

**Closed by JanKallman** 2020-04-27 07:12 UTC
