### ISSUE TITLE
Bad Signature BadReadException On Valid Excel File

### ISSUE THREAD

**Issue by BryceBarbara** [EPPlusSoftware/EPPlus#605] opened 2022-02-25 20:14 UTC
I have an excel file that loads file in Excel, opens just fine in 7Zip, but then causes a "Bad signature" `BadReadException` to be thrown when EPPlus tries to load it. Unfortunately I'm unable to share the excel file due to the sensitive nature of it.

However I've done a bit of looking into it and it seems to be caused by EPPlus doing some funky stuff in the ZIP parsing logic. I've cloned the repo locally and can get the file to load without issue if I switch the following if statement to `if (false)`:

https://github.com/EPPlusSoftware/EPPlus/blob/d46ffcc90636c213ea162fa23a3f6d86ed8da0d9/src/EPPlus/Packaging/DotNetZip/ZipEntry.Read.cs#L161

I guess my question is: Why is this if statement here? What purpose does it serve? Can it be removed since it causes the file offset to get messed up and leads to `BadReadException` when reading further ZipEntries?

**Comment by JanKallman** [comment] 2022-02-28 09:41
I will need your workbook to be able to see what the problem is. If you have a commercial license, you can upload the workbook in our support portal.

**Comment by BryceBarbara** [comment] 2022-03-01 20:04
Although we do have a commercial license, it's unlikely that I'll be able to get permission from management to share this workbook. It'll take a lot of effort on my part to get that permission, so I'd like to avoid that if possible. 

However, maybe I can explain what I think is messed up with the code?

##  Bug explanation attempt

This code searches for a specific signature to find the next zip data descriptor in the file:
https://github.com/EPPlusSoftware/EPPlus/blob/d46ffcc90636c213ea162fa23a3f6d86ed8da0d9/src/EPPlus/Packaging/DotNetZip/ZipEntry.Read.cs#L196

But that assumes that those bytes won't show up in any of the ZipEntry's compressed data, which I don't think is a valid assumption. 

In my case, there is an instance of those 4 bytes in the middle of the compressed data:
![image](https://user-images.githubusercontent.com/24460210/156238419-5d556ead-8a50-4aea-bbff-162faadd2395.png)

Due to that, the code inside the loop executes twice, specifically this:
https://github.com/EPPlusSoftware/EPPlus/blob/d46ffcc90636c213ea162fa23a3f6d86ed8da0d9/src/EPPlus/Packaging/DotNetZip/ZipEntry.Read.cs#L238

Which then causes this code to erroneously seek 16 bytes past where it should:
https://github.com/EPPlusSoftware/EPPlus/blob/d46ffcc90636c213ea162fa23a3f6d86ed8da0d9/src/EPPlus/Packaging/DotNetZip/ZipEntry.Read.cs#L375

## Proposed solution 1

I was able to fix it by changing the following:
https://github.com/EPPlusSoftware/EPPlus/blob/d46ffcc90636c213ea162fa23a3f6d86ed8da0d9/src/EPPlus/Packaging/DotNetZip/ZipEntry.Read.cs#L196-L200

to:

```c#
long d = Ionic.Zip.SharedUtilities.FindSignature(ze.ArchiveStream, ZipConstants.ZipEntryDataDescriptorSignature);
if (d == -1) return false;

// avoid scenarios where the signature is found in the middle of the entry data
if (ze._CompressedSize != 0 && ze._CompressedSize > d) d = ze._CompressedSize;

// total size of data read (through all loops of this).
SizeOfDataRead += d;
```

## Proposed solution 2

Although not my favorite, you could change:
https://github.com/EPPlusSoftware/EPPlus/blob/d46ffcc90636c213ea162fa23a3f6d86ed8da0d9/src/EPPlus/Packaging/DotNetZip/ZipEntry.Read.cs#L238

to:
```c#
ze._LengthOfTrailer = 16;  // bytes including sig, CRC, Comp and Uncomp sizes 
```

**Comment by JanKallman** [comment] 2022-03-02 12:44
Where is the workbook you use created? I have not seen this issue before. Is it saved in Excel? 
As this issue occurs in the DotNetZip extraction, can you delete the sensitive data (/xl/sheet etc) in the package (with 7zip or similar) and keep the issue to occur? Modifying the code as proposed without fully understand the issue is very difficult and risky.

**Comment by BryceBarbara** [comment] 2022-03-02 21:48
I believe this workbook was created and saved in Excel but it also could've been saved by EPPlus, I'm not totally sure what the user did to create a workbook with this sequence of bytes in the ZIP file. 

I managed to manually create an excel file that recreates a bit of what I'm seeing. It's still technically a valid zip file (although you'll need to disable the CRC checking because I manually edited some bytes) but EPPlus fails to load it due to the bugged code. 7Zip has no such issue.

[Book1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/8173149/Book1.xlsx)

**Comment by JanKallman** [comment] 2022-03-03 08:38
Great, thanks, I'll have a look at it.

**Comment by JanKallman** [comment] 2022-03-04 08:27
This file is corrupt. It fails on finding the signature in the header for sheet3.xml. 7zip also reports that the header for this file is corrupt.
If you re-save your failing workbook in Excel, do you still get the same issue?

**Comment by JanKallman** [comment] 2022-03-04 08:58
I also tried the proposed fix (solution 1), but it causes the extraction to hang.

**Comment by BryceBarbara** [comment] 2022-03-04 16:30
Thank you for looking at it!

I think I just failed at recreating a proper ZIP file that displays the bug while also being a valid file. 7Zip does indeed choke on the `Book1.xlsx` file I manually modified in an attempt recreate the behavior of the real excel file causing me issues. However, 7Zip has no such issues with the real file. I'll see if I can invest more time into this and create a valid excel file that exhibits the bug.

**Comment by JanKallman** [comment] 2022-05-03 12:10
I have added a fix for this issue as I received a workbook with a similar issue. Can you try latest develop build and see if it works with your workbook? See https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by JanKallman** [comment] 2022-05-19 06:09
I'll close this issue as a fix has been applied. If you still have an issue with this feel free to re-open it.

**Closed by JanKallman** 2022-05-19 06:09 UTC

**Comment by DannyBoyk** [comment] 2025-01-10 20:33
@BryceBarbara - we have come across this exact same issue:
https://github.com/EPPlusSoftware/EPPlus/issues/1808

**Comment by BryceBarbara** [comment] 2025-01-10 21:51
@DannyBoyk I was unable to get a proper fix from them and had to manually work around it instead. Hopefully, you can provide them with an example file where I was not.
