### ISSUE TITLE
Issues with EPPlus package version 5.8.3 and 6.1.2

### ISSUE THREAD

**Issue by SubhadipBhanja** [EPPlusSoftware/EPPlus#802] opened 2023-02-20 07:01 UTC
While we are updating the EPPlus package version from 4.5.3.2 to 5.8.3 then we could able to see the special characters like _x000D_ getting appended after the text in cell but which was working fine in 4.5.3.2 version with the same piece of code. Same issue is happening for the latest version 6.1.2 as well.

example: Test Client_x000D_

![screenshot_issue](https://user-images.githubusercontent.com/46018823/220037796-6102288c-ec3b-4c2d-980f-22790848342f.png)

Attached the screenshot of the issue.

Please suggest the resolution with the version 5.8.3..Thanks!

**Comment by JanKallman** [comment] 2023-02-20 07:37
That is the encoded value. Please use `\r` for carrige return and `\n` for line feed.

**Comment by UrviBhatt** [comment] 2023-02-21 09:47
@JanKallman   Thanks for your response. Actually in the earlier version(4.5.3.2), its never converted \r into encoded value. For 5.8.3 version \r converting into _x000D_ at the end. Please help us how we can resolve the issue in 5.8.3 or above version

**Comment by JanKallman** [comment] 2023-02-21 10:36
Later version of EPPlus will encode values, so supplying an encoded value will not work. Doesn't "\r" work or what is the problem?

**Comment by UrviBhatt** [comment] 2023-02-21 11:02
Please find the below scenario where the issue is happening for version 5.8.3 and above:
While we are passing \r at the end of the text like below:

`using (ExcelRange Rng = wsSheet1.Cells[2, 2, 2, 2])       
 {            
           Rng.Value = "Test Client\r";        
 }` 
 
Getting the output in the spreadsheet compare like below: **Test Client_x000D_** , but same thing for the version 4.5.3.2, not appending any encoded values, internally taking care of the \r.

Please let us know your thought and resolution for the issue and it would be great if we can connect and discuss in any platform. Thanks for your support.

**Comment by JanKallman** [comment] 2023-03-15 15:07
I'm not sure I understand the issue. I don't get that output when I try this test...
```C#
        [TestMethod]
        public void i802()
        {
            using (var package = OpenPackage("I802.xlsx"))
            {
                var ws = package.Workbook.Worksheets.Add("sheet1");
                using (ExcelRange Rng = ws.Cells[2, 2, 2, 2]) 
                { 
                    Rng.Value = "Test Client\r"; 
                }
                SaveAndCleanup(package);            
            }
        }

```
![image](https://user-images.githubusercontent.com/982881/225351914-5c18dc16-04ec-49bb-9e0f-c8029af8d62f.png)
Can you provide a full test to reproduce and describe your issue.

**Comment by JanKallman** [comment] 2023-03-23 13:49
I'll close this issue. Feel free to re-open with some code to describe the issue

**Closed by JanKallman** 2023-03-23 13:49 UTC
