### ISSUE TITLE
Group/UnGroup issues Epplus 5.5.0

### ISSUE THREAD

**Issue by BritishFan** [EPPlusSoftware/EPPlus#264] opened 2020-12-28 07:20 UTC
In comparison to 4.5.3 vs later version has issues related to setting up of Texts in excel with column not getting ACROSS selection. As seen in below screen.

![IMG_20201228_110641](https://user-images.githubusercontent.com/8280722/103196912-0d355900-490b-11eb-9eae-9df811d39f11.jpg)

Where the first one is on older epplus and the 2nd one on the right is based of newest epplus ( 5.5.0), the values are getting hidden when outline in set on rows. 

Please let me know if more logs / testing is required. Thanks.

**Comment by JanKallman** [comment] 2020-12-28 07:31
I'll have a look. Thanks for reporting it.

**Comment by JanKallman** [comment] 2020-12-28 07:57
I have trouble reproducing this. Can you provide some sample code and if needed a template workbook,

**Comment by JanKallman** [comment] 2021-01-19 08:02
I close this for now as I cant reproduce this. Please reopen if you can add a test case to reproduce.

**Closed by JanKallman** 2021-01-19 08:02 UTC
