### ISSUE TITLE
System.Xml.XmlException: 'The 'worksheet' start tag on line 2 position 2 does not match the end tag of 'c'. Line 29, position 15.'

### ISSUE THREAD

**Issue by PMF-Constantin** [EPPlusSoftware/EPPlus#601] opened 2022-02-23 09:06 UTC
We have a valid XLSX which generates this Error. When unzipping the XLSX all XMLs are valid.

We have narrowed down the issue to the size of the Sheet XMLs:
In the affected XLSX there are two sheets Sheet5 and Sheet2. In the one not working we have added spaces to the Sheet5 XML (which should not change the validity of the XML)

Not working:
![image](https://user-images.githubusercontent.com/80812807/155288063-f0fb2818-315a-4ee9-99d7-63dcc7cf16c6.png)
Working:
![image](https://user-images.githubusercontent.com/80812807/155288145-d026485d-0ac9-44ee-b0bc-46b710b1d0ac.png)

I looks as if the library is not loading the whole XML for some reason if the XML is too long. It will however load, if opened and saved again with Excel. This leads us to believe, the library is somehow guessing the size of the XML and if saved with Excel, Excel is somewhere providing the correct number. Even so, the library should still always load the whole file.

**Comment by JanKallman** [comment] 2022-02-24 07:27
Please attach you workbook so we can replicate this.

**Comment by JanKallman** [comment] 2022-03-11 08:08
I can't reproduce this issue without a workbook, so I'll close this issue. Feel free to re-open it if you can attach your workbook.

**Closed by JanKallman** 2022-03-11 08:08 UTC
