### ISSUE TITLE
Enable Zip64

### ISSUE THREAD

**Issue by aminebizid** [EPPlusSoftware/EPPlus#114] opened 2020-05-21 09:27 UTC
Hello,
I get this error when invoking GetAsByteArrayAsync()

`OfficeOpenXml.Packaging.Ionic.Zip.ZipException: Compressed or Uncompressed size, or offset exceeds the maximum value. Consider setting the UseZip64WhenSaving property on the ZipFile instance.`

How can I enable Zip64 compression for huge files?

**Comment by JanKallman** [comment] 2020-05-22 06:58
This is a duplicate of https://github.com/EPPlusSoftware/EPPlus/issues/86
EPPlus only support zip32 at this stage.

**Closed by JanKallman** 2020-05-22 06:58 UTC
Labels: duplicate

**Comment by JanKallman** [comment] 2020-07-22 15:28
Enabled Zip64 in version 5.2.1
