### ISSUE TITLE
Fails to copy cells when data validation or conditional formatting is set (version 5.8.0)

### ISSUE THREAD

**Issue by terasato** [EPPlusSoftware/EPPlus#527] opened 2021-11-05 05:42 UTC
### Summary
`ExcelRangeBase.Copy` fails when data validation or conditional formatting is set to the `sourceRange`.
Clearing `DataValidations` and `ConditionalFormattings` temporarily resolve this issue.

### Version
Version `5.8.0`
(I confirmed this does not happens with version `5.7.4`.)

### Exception details
```
Message:
  Specified argument was out of the range of valid values. (Parameter 'Start cell Address must be less or equal to End cell address')

ParamName:
  Start cell Address must be less or equal to End cell address

StackTrace:
   at OfficeOpenXml.ExcelAddressBase.Validate()
   at OfficeOpenXml.ExcelAddressBase..ctor(Int32 fromRow, Int32 fromCol, Int32 toRow, Int32 toColumn)
   at OfficeOpenXml.Core.RangeCopyHelper.HandelAddress(ExcelAddressBase cfAddress)
   at OfficeOpenXml.Core.RangeCopyHelper.CopyDataValidations()
   at OfficeOpenXml.Core.RangeCopyHelper.Copy()
   at OfficeOpenXml.ExcelRangeBase.Copy(ExcelRangeBase Destination)
```

**Comment by terasato** [comment] 2021-11-05 05:52
30180ef1c7c7c8db949c745ce6506716e22fb9c3 is smelling... I will look into this...

Hi @JanKallman , thank you for enhancing `RangeCopyHelper`. I think you are an expert in this area. Do you have any input on this issue?

**Comment by JanKallman** [comment] 2021-11-05 08:04
Yes, this functionality was added in 5.8. I'll have a look if I can reproduce your issue. Otherwise can you provide some code to reproduce this?

**Comment by JanKallman** [comment] 2021-11-05 13:38
I can't reproduce this. Can you provide some code to reproduce this exception?

**Comment by JanKallman** [comment] 2021-11-09 09:30
This should be fixed now. Try latest develop nuget package...https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by terasato** [comment] 2021-11-09 11:01
Thank you @JanKallman, I confirmed that the issue has been fixed 😃

**Comment by terasato** [comment] 2021-11-09 11:04
Could you let me know when this is fixed in the release version?

**Comment by JanKallman** [comment] 2021-11-09 13:07
We will do a release this or next week.

**Comment by JanKallman** [comment] 2021-11-22 11:37
Fixed in EPPlus 5.8.3

**Closed by JanKallman** 2021-11-22 11:37 UTC
Labels: bug

**Comment by divakaraj** [comment] 2023-11-15 12:45
@JanKallman 
We got this error in our application from an older version, and upgrading to a recent version fixed the issue for us.
We are able to replicate it only with specific data, so we aren't sure on why it's caused.
If possible, could you please provide on what the issue was, and what was done to fix it. Thanks in advance Jan

**Comment by JanKallman** [comment] 2023-11-15 12:57
This commit : https://github.com/EPPlusSoftware/EPPlus/commit/cbacac1a2b629e349b33b0f88f98d20682fffbdf
fixed this issue. It was a problem when copying ranges with Data validations and Conditional formatting.
