### ISSUE TITLE
ArgumentOutOfRangeException when Saving after worksheet copy

### ISSUE THREAD

**Issue by steph9111** [EPPlusSoftware/EPPlus#88] opened 2020-04-18 17:54 UTC
ArgumentOutOfRangeException

        Dim _ExcelApplication As ExcelPackage = New ExcelPackage(New IO.FileInfo("ExcelFile1.xlsm"))
        Dim _ExcelApplication2 As ExcelPackage = New ExcelPackage(New IO.FileInfo("ExcelFile2.xlsx"))

        Dim _SheetToCopy As ExcelWorksheet = _ExcelApplication.Workbook.Worksheets(1)

        _ExcelApplication2.Workbook.Worksheets.Add("test", _SheetToCopy)

        _ExcelApplication2.Save()

or 

 Dim bin As Byte() = _ExcelApplication2.GetAsByteArray()

**Comment by JanKallman** [comment] 2020-04-20 08:50
Please attach the Excel file so I can reproduce this issue.

**Comment by steph9111** [comment] 2020-04-20 12:19
Hi, thank's for your answer. Run perfectly with another simple workbook,
but not with this worbook.

Normally they have 10 sheets with complex relation ship.

I deleted all of sheet less one.

Cordially

Stéphane

**Comment by JanKallman** [comment] 2020-04-21 06:47
Can you attach the workbook to this issue?

**Comment by steph9111** [comment] 2020-04-21 11:00
[
[FILE1.zip](https://github.com/EPPlusSoftware/EPPlus/files/4509530/FILE1.zip)

](url)

**Comment by JanKallman** [comment] 2020-04-22 10:07
Thanks,
The problem is that the copied worksheet contains two buttons, which isn't yet supported by EPPlus. We will look into this in the coming versions.
This causes the copy to fail. I'll see if I can add a short term fix for this.

**Comment by steph9111** [comment] 2020-04-22 10:16
Thank's,

But 2 questions:

1°) Is it possible to delete this buttons in this excel file before copying?

2°) Why no exist the "PasteSpecial" function in EPPLUS? Because the copy
method of row and cells no return the igual style, format and cells value
that the source file..

**Comment by JanKallman** [comment] 2020-04-22 12:06
I have fixed the dispose issue when saving, but as the sheet contains Controls (buttons) the copied worksheet will be corrupt.

1. No, not with EPPlus out of the box. You will have to delete the related package parts for the Controls and the nodes in the vml part.
2. Unsure what you mean. Do you want to copy the values only?

**Comment by steph9111** [comment] 2020-04-22 12:50
`  Dim _ExcelApplication As ExcelPackage = New ExcelPackage(New IO.FileInfo("File1.xlsm"))
        Dim _ExcelApplicationCopy As ExcelPackage = New ExcelPackage(New IO.FileInfo("File2.xlsx"))
        Dim wsheet As ExcelWorksheet = _ExcelApplicationCopy.Workbook.Worksheets.Add("ResultCopy")

        _ExcelApplication.Workbook.Worksheets("SheetToCopy").Cells("A1:AX50").Copy(wsheet.Cells("A1:AX50"), ExcelRangeCopyOptionFlags.ExcludeFormulas)

        _ExcelApplicationCopy.Save()`

I'm trying with :

`        For i As Integer = 1 To 50
            wsheet.Row(i).StyleID = _ExcelApplication.Workbook.Worksheets("fiche fab").Row(i).StyleID
        Next`

Same Result.

SheetToCopy:
![source](https://user-images.githubusercontent.com/43347051/79983770-9643e880-847e-11ea-8be9-0552cd0ac002.PNG)

Result:
![dest1](https://user-images.githubusercontent.com/43347051/79983803-a3f96e00-847e-11ea-9f45-0c2f03df7a43.PNG)

**Comment by JanKallman** [comment] 2020-04-27 11:01
Closing this issue. 
Can't reproduce the last comment as I don't have the xlsx file. Please open a new issue if this is something we should look into.

**Closed by JanKallman** 2020-04-27 11:01 UTC
Labels: bug
