### ISSUE TITLE
Workbook with many names created using EPPlus is very slow to open in Excel

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#1238] opened 2024-01-05 12:48 UTC
I have a workbook created by EPPlus which takes about 5 minutes to open in Excel. After I press 'save' in Excel, the workbook only takes a few seconds to open the next time.

I've tracked down the cause of this to the order of the `definedName`s in the `workbook.xml` part. EPPlus puts these in the order they were created (I think?) whereas Excel orders them by the value of the `name` attribute:

```xml
...
<definedNames>
        <definedName name="_R0000_C0000" localSheetId="0">Sheet1!$A$1</definedName>
        <definedName name="_R0000_C0000" localSheetId="9">Sheet10!$A$1</definedName>
        <definedName name="_R0000_C0000" localSheetId="10">Sheet11!$A$1</definedName>
        <definedName name="_R0000_C0000" localSheetId="11">Sheet12!$A$1</definedName>
        <definedName name="_R0000_C0000" localSheetId="12">Sheet13!$A$1</definedName>
        <definedName name="_R0000_C0000" localSheetId="13">Sheet14!$A$1</definedName>
        ...
        (The workbook has over 100,000 names.)
        ...
</definedNames>
...
```

It seems Excel is optimised for those names to appear in a specific order. Would it be possible for EPPlus to use the same ordering?

I've attached an example workbook I created to demonstrate the problem - this one takes about 1 minute to load for me, and 3 seconds to load after saving in Excel.

Many thanks.

[TestVerySlowWorkbook.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13842169/TestVerySlowWorkbook.xlsx)
[TestVerySlowWorkbook_SavedInExcel.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13842171/TestVerySlowWorkbook_SavedInExcel.xlsx)

**Comment by OssianEPPlus** [comment] 2024-01-08 09:44
Hia! We're looking into this. After some fiddling with the files it does seem that this is the cause. It should be possible to use the same ordering. We'll look at it for a bit to ensure there's not some other underlying cause and get back to you.

**Comment by OssianEPPlus** [comment] 2024-01-09 13:14
We've slated a fix for this for next release but it should now be available in our [NuGet Develop Feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed). Thanks for noticing and telling us, and for doing some sleuthing of your own! It's highly appreciated

**Closed as completed** 2024-01-12 13:10 UTC
