### ISSUE TITLE
Editing xlsx file

### ISSUE THREAD

**Issue by robertovaldesperez** [EPPlusSoftware/EPPlus#478] opened 2021-09-02 15:51 UTC
Pivot Cache with id 6 is invalid . Contains reference to an column with empty header

**Comment by JanKallman** [comment] 2021-09-03 06:32
Ok, can you attach a way to reproduce?

**Comment by robertovaldesperez** [comment] 2021-09-03 07:22
Hi @JanKallman,

Now, i'm using Epplus version: 5.7.4

File content:
[prueba nueva.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7103811/prueba.nueva.xlsx)

My code:

`public static readonly Dictionary<string, string> ASSET_FIELDS = new Dictionary<string, string>
{
	{ string.Empty, "Select one..." },
	{ "APPRAISAL_DATE", "Appraisal Date" },
	{ "APPRAISAL_AREA", "Appraisal Surface" },
	{ "APPRAISAL_AREA_CCAA", "Appraisal Surface w/CCAA" },
	{ "APPRAISAL_VALUE", "Appraisal Value" },
	{ "AURA" + "." + "REFERENCE", "Aura ID" },
	{ "BATHROOMS", "Bathroom" },
	{ "BORROWER_ID", "Borrower ID" },
	{ "AREA_CCAA", "Built surface w/CCAA" },
	{ "CADASTRAL_REFERENCE", "Cadastral reference" },
	{ "DEVELOPMENT" + "." + "CLIENT_GROUP_ID", "Client Development ID" },
	{ "CLIENT_ID", "Client ID" },
	{ "YEAR_OF_CONSTRUCTION", "Construction Year" },
	{ "COUNTRY", "Country" },
	{ "CROSSING_DOCKS", "Crossing Docks" },
	{ "DATE_OF_DISQUALIFICATION", "Date of desaffection - Social Housing" },
	{ "LEADER" + "." + "REFERENCE", "Dependency Reference" },
	{ "DEVELOPMENT" + "." + "REFERENCE", "Development ID" },
	{ "ADDRESS_DOOR", "Door" },
	{ "DUPLEX", "Duplex" },
	{ "ELEVATOR", "Elevator" },
	{ "ADDRESS_FLOOR", "Floor" },
	{ "FULL_ADDRESS", "Full Address" },
	{ "IDUFIR", "IDUFIR" },
	{ "ILLEGAL_SQUATTERS", "Illegal Squatters" },
	{ "ORIENTATION", "Interior/Exterior" },
	{ "LATITUDE", "Latitude" },
	{ "LIEN", "Lien" },
	{ "LOAN_ID", "Loan ID" },
	{ "LONGITUDE", "Longitude" },
	{ "MAINTENANCE_STATUS", "Maintenance Status" },
	{ "MARKET_SHARE", "Market Share (%)" },
	{ "LEGAL_MAXIMUM_VALUE", "Max. Value - Social Housing" },
	{ "MAX_HEIGHT", "Maximum Height" },
	{ "VPO_MODULE", "Module - Social Housing" },
	{ "MUNICIPALITY", "Municipality" },
	{ "NEGATIVE_COLD", "Negative Cold" },
	{ "ADDRESS_NUMBER", "Number" },
	{ "BORROWER", "Owner" },
	{ "PARKINGS", "Parking" },
	{ "PERIMETER", "Perimeter" },
	{ "PLOT_AREA", "Plot Surface" },
	{ "POSITIVE_COLD", "Positive Cold" },
	{ "PROVINCE", "Province" },
	{ "REFERENCE", "Reference ID" },
	{ "REGISTRATION", "Registry" },
	{ "REGISTRY_ID", "Registry ID" },
	{ "REGISTRATION_NUMBER", "Registry Number" },
	{ "AREA_REGISTRY", "Registry Surface" },
	{ "AREA_CCAA_REGISTRY", "Registry Surface w/CCAA" },
	{ "RENTED", "Rented" },
	{ "REPEATED", "Repeated" },
	{ "ROOMS", "Rooms" },
	{ "SCOPE", "Scope" },
	{ "SEA_VIEWS", "Sea Views" },
	{ "MONTHLY_COMM_EXP_SQM", "Service Charges" },
	{ "SMOKE_VENT", "Smoke Ventilation" },
	{ "VPO", "Social Housing" },
	{ "DEVELOPMENT" + "." + "PROPERTY_STATUS", "Status" },
	{ "STOREROOMS", "Storage" },
	{ "ADDRESS_NAME", "Street" },
	{ "ASSET_SUBTYPE", "Sub-typology" },
	{ "AREA", "Surface" },
	{ "SWIMMING_POOL", "Swimming Pool" },
	{ "TERRACE", "Terrace" },
	{ "TERRACE_AREA", "Terrace Surface" },
	{ "ACTIVITY", "Type of activity" },
	{ "STATE", "Type of product" },
	{ "ASSET_TYPE", "Typology" },
	{ "USEFUL_AREA", "Useful Surface" },
	{ "VALUATION_TYPE", "Valuation Type" },
	{ "ZIP_CODE", "Zip Code" }
}`

`public class Error
{
	public string TypeOfError { get; set; }
	public int Row { get; set; }
	public int Col { get; set; }
	public List<string> Messages { get; set; }
}`

`public class AssetField
{
	public int Index { get; set; }
	public string Field { get; set; }
}`

`public async Task<byte[]> DownloadSummaryFile(byte[] content)
{

	var dataStartRow = 2;
	var errors = JsonConvert.DeserializeObject<Error[]>("[{\"typeOfError\":\"WARNING\",\"row\":4,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":20,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":35,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":47,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":57,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":60,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":90,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":131,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":136,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":138,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]},{\"typeOfError\":\"WARNING\",\"row\":139,\"col\":17,\"messages\":[\"The address is uncompleted. It can only get an approximate coordinates.\"]}]");
	var assetFields = JsonConvert.DeserializeObject<AssetField[]>("[{\"index\":1,\"field\":\"Reference\"},{\"index\":15,\"field\":\"ZipCode\"},{\"index\":16,\"field\":\"Municipality\"},{\"index\":17,\"field\":\"FullAddress\"}]");

	using var excelPackage = new ExcelPackage();
	await excelPackage.LoadAsync(new System.IO.MemoryStream(content));
	var worksheet = excelPackage.Workbook.Worksheets["Avances"];
	var start = worksheet.Dimension.Start;
	var end = worksheet.Dimension.End;

	// Add column of errors and warnings
	var startMessagesColumn = end.Column + 1;
	worksheet.InsertColumn(startMessagesColumn, 2);
	var errorColumn = startMessagesColumn;
	var warningColumn = startMessagesColumn + 1;
	worksheet.Cells[(dataStartRow ?? 0) - 1, errorColumn].Value = "Errors";
	worksheet.Cells[(dataStartRow ?? 0) - 1, warningColumn].Value = "Warnings";
	foreach (var error in errors)
	{
		if (error.TypeOfError == "ERROR")
		{
			worksheet.Cells[error.Row - 1, errorColumn].Value += string.Join(" ", error.Messages.Select(w => string.Format("{0} {1}", ASSET_FIELDS.GetValueOrDefault(assetFields.Where(x => x.Index == error.Col).Select(x => x.Field).FirstOrDefault()), w)));
		}
		else
		{
			worksheet.Cells[error.Row - 1, warningColumn].Value += string.Join(" ", error.Messages.Select(w => string.Format("{0} {1}", ASSET_FIELDS.GetValueOrDefault(assetFields.Where(x => x.Index == error.Col).Select(x => x.Field).FirstOrDefault()), w)));
		}
	}

	// Remove distinct columns from "Reference"
	var colFieldReference = assetFields.Where(x => x.Field == "REFERENCE").Select(x => x.Index).FirstOrDefault();
	worksheet.Cells[1, colFieldReference + 1].Value = "Reference";

	var deletedColumns = 0;
	for (int i = 1; i <= end.Column; i++)
	{
		if (colFieldReference + 1 != i && errorColumn != i && warningColumn != i)
		{
			worksheet.DeleteColumn(i - deletedColumns);
			deletedColumns++;
		}
	}

	// Remove rows that do not contain errors
	var deletedRows = 0;
	for (int i = 1; i <= end.Row; i++)
	{
		if (i < (dataStartRow - 1) || (i >= dataStartRow && !errors.Any(w => (w.Row - 1) == i)))
		{
			worksheet.DeleteRow(i - deletedRows);
			deletedRows++;
		}
	}
	return await excelPackage.GetAsByteArrayAsync();
}`

Thanks a lot

**Comment by JanKallman** [comment] 2021-09-03 11:44
The problem seems to be the pivot table in sheet **Calendario Entregas**. The fields in the cache does not match the source range. Likley due to inserted columns in the source area. 
As a workaround you can refresh the pivot table in the input file(prueba nueva.xlsx) and all seems to work as expected. 
I will look more into this and supply a fix for this issue.

**Comment by robertovaldesperez** [comment] 2021-09-07 08:02
I also tried to remove the **Calendario Entregas** tab but Epplus did not allow it. Nor does it throw an error. If it is of any help.

**Comment by JanKallman** [comment] 2021-09-07 13:59
Hello, 
The problem is that the pivot tables in your Excel file does not match the source range. 
You can likely fix this by open the template file, prueba nueva.xlsx, and refresh the 6 pivot tables in the workbook (PivotTable Analyze-->Refresh button). This will update the fields with the the source ranges.
I'm working on a fix for this actual issue that will be available shortly.

**Comment by JanKallman** [comment] 2021-09-21 12:22
Version 5.7.5 should solve this issue.

**Closed by JanKallman** 2021-09-21 12:22 UTC
Labels: bug
