### ISSUE TITLE
Object reference not set to an instance of an object in version 5.4.0

### ISSUE THREAD

**Issue by MoRooz** [EPPlusSoftware/EPPlus#195] opened 2020-10-12 05:08 UTC
after upgrade to 5.4.0 i got this error, after downgrade to 5.3.2 problem solved

System.NullReferenceException: Object reference not set to an instance of an object.
   at OfficeOpenXml.Packaging.ZipPackage.PartExists(Uri partUri)
   at OfficeOpenXml.Table.PivotTable.PivotTableCacheInternal.ResetRecordXml(ZipPackage pck)
   at OfficeOpenXml.ExcelWorkbook.SavePivotTableCaches()
   at OfficeOpenXml.ExcelWorkbook.Save()
   at OfficeOpenXml.ExcelPackage.Save()
   at OfficeOpenXml.ExcelPackage.SaveAs(Stream OutputStream)

**Comment by JanKallman** [comment] 2020-10-12 06:44
Can you provide me with a reproducible sample?

**Comment by MoRooz** [comment] 2020-10-12 20:09
`class Program
    {
        static void Main(string[] args)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            var template = new FileInfo("test.xlsx");
            using (var file = new ExcelPackage(template))
            {
                var ws = file.Workbook.Worksheets[1];
                var stream = new MemoryStream();
                file.SaveAs(stream);
            }
        }
    }`

**Comment by JanKallman** [comment] 2020-10-13 08:32
Thanks,
I'll supply a fix shotly. This issue occures  when the pivot table option  'Save source data with file' is set to false under the data tab.
As a quickfix check this checkbox in the input xlsx file.

**Comment by mortalwind** [comment] 2020-10-21 06:17
![error](https://user-images.githubusercontent.com/10827477/96680432-2acfca80-137e-11eb-9041-e12306b14a89.jpg)
![result](https://user-images.githubusercontent.com/10827477/96680435-2c00f780-137e-11eb-8981-cc1e161533b6.jpg)
My object is not null but it throws an error.

**Comment by JanKallman** [comment] 2020-10-21 11:27
@mortalwind I can not see what the error is on this screenshot, so I am unsure if it is related to this issue.

**Comment by mortalwind** [comment] 2020-10-21 11:40
As you can see in red box, worksheets are loading successfully. But when I try to assign this to an object, Epplus.dll throw "Object reference not set to an instance of an object" error.  I think,it is same issue.

**Comment by JanKallman** [comment] 2020-10-21 12:17
In that case this issue is resolved and will go out with our next release. Feel free to try it out using our develop nuget feed. 
https://ci.appveyor.com/project/EPPlusSoftware/epplus/build/artifacts

**Comment by mortalwind** [comment] 2020-10-21 12:22
OK. I stopped using EPPlus anyway. I just wanted to report a bug. Because I have no time to waiting for new version.

**Comment by JanKallman** [comment] 2020-11-05 14:37
Fixed in 5.4.1

**Closed by JanKallman** 2020-11-05 14:37 UTC
Labels: bug

**Comment by souleymanebd** [comment] 2021-04-23 22:26
Hello, I have two similar issues with EPPLUS (version 5.6.3.0) copying one sheet with pivot table + chart to another workbook:
-------
excel.Workbook.Worksheets.Add(excelTemplate.Workbook.Worksheets(4).Name, excelTemplate.Workbook.Worksheets(4))
'excel.Workbook.Worksheets.Add(excelTemplate.Workbook.Worksheets(6).Name, excelTemplate.Workbook.Worksheets(6))
------
The first one is throwing this error : 'System.Exception' in EPPlus.dll - Internal error: Pivot table uri does not exist in package.
The second : 'System.NullReferenceException' in EPPlus.dll - Object reference not set to an instance of an object.

Any advise please

**Comment by rpath2000** [comment] 2021-07-13 20:13
I have similar issue to report.. when I copy an excel document with macro and try to add a new page, it throws this error: "errorMessage": "Object reference not set to an instance of an object.",
Sample code:
ExcelPackage ep= new ExcelPackage(myfile);
var ws = ep.Workbook.Worksheets.Add(sheetName); <== error out here

I am using version 5.7.1 (latest stable release) 
This works if I remove the macros from excel.

**Comment by ThomasSoftware** [comment] 2021-09-02 21:00
I get the same issue as rpath2000 in version 5.5.0, 5.7.1, and 5.7.4 (Latest Stable Release) 

the furthest I can go back is 5.5.0 because I use the add button control feature. My workbook has macros in it. If I remove the macros it works but then my workbook doesn't work because it needs the macros.
