### ISSUE TITLE
ExcelWorkbook.Worksheets.Add() copying same image to different worksheet

### ISSUE THREAD

**Issue by SowjanyaMadala** [EPPlusSoftware/EPPlus#99] opened 2020-04-29 15:02 UTC
I am having same issue as discussed in these threads 
(https://github.com/dfinke/ImportExcel/issues/513)
(https://github.com/JanKallman/EPPlus/issues/394). Looks like the issue is not fixed in recent version.

We are planning to buy the license but stuck in this. Please help.

**Comment by JanKallman** [comment] 2020-04-30 06:24
I'll have a look

**Comment by JanKallman** [comment] 2020-04-30 12:09
Please try latest develop build from this feed...
https://ci.appveyor.com/nuget/epplus

**Comment by JanKallman** [comment] 2020-04-30 14:06
Its a nuget feed for our develop builds. 
Add the link into Visual Studio - Options -> Nuget Package Manager - Package Sources, to access the package. Optionally you can Clone the develop branch and build it yourself.

**Comment by SowjanyaMadala** [comment] 2020-05-01 02:10
This development feed looks good. May I know when this will be available in release mode ?

**Comment by SowjanyaMadala** [comment] 2020-05-01 02:16
And I have one more small issue. Not sure if there is any property already available while copying the worksheet. Please guide me.

I have Excel1 file (attached) and when I copy it to another file, it is changing the cell format. (output file attached)
[Excel1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4562246/Excel1.xlsx)
![output](https://user-images.githubusercontent.com/49454710/80776327-242f6b80-8b30-11ea-9060-0c394a074311.PNG)

**Comment by JanKallman** [comment] 2020-05-01 10:28
They look identical when i Copy the worksheet. Do you use the Worksheets.Add method with your worksheet as second paramenter…
`p2.Workbook.Worksheets.Add("copy1", p.Workbook.Worksheets[0]);`

**Comment by SowjanyaMadala** [comment] 2020-05-01 13:22
yes, I am using in a foreach loop:
  foreach (ExcelWorksheet srcWorkSheet in srcPkgReports.Workbook.Worksheets)
                                        {
                                            destPkgWorking.Workbook.Worksheets.Add(sheetName, srcWorkSheet);
                                        }

**Comment by JanKallman** [comment] 2020-05-04 06:38
I can not reproduce this issue. Do you have a xlsx file that you copy to as well?

**Comment by SowjanyaMadala** [comment] 2020-05-05 02:26
We have our company Logo in those files, so I can't post it here. Could you try adding the picture with below properties and see if you can reproduce ?
![image](https://user-images.githubusercontent.com/49454710/81030261-37a34500-8e56-11ea-9ba3-317aef627fca.png)

**Comment by JanKallman** [comment] 2020-05-05 06:04
Does this work if you remove the logo or do you get the same issue?

**Comment by SowjanyaMadala** [comment] 2020-05-05 12:55
yes, it works fine if I change the image or remove it.

**Comment by SowjanyaMadala** [comment] 2020-05-05 12:56
but there are nearly 250 reports which has this logo.. I cannot ask them to modify it in each report..

**Comment by JanKallman** [comment] 2020-05-05 13:16
No, I just wanted to know if the logo image is the issue. I'll see if I can reproduce it by adding the image.

**Comment by JanKallman** [comment] 2020-05-06 10:57
I think I can reproduce this and it is related to image scaling. I think the problem occures when image coordinates are fractions of a pixel in the scaling. I will provide a fix, but it will take some time.

**Comment by SowjanyaMadala** [comment] 2020-05-06 13:16
I am glad that you are able to reproduce. Thank you!

**Comment by JanKallman** [comment] 2020-05-11 06:14
Can you give the latest develop build a try to see if it solves your problem?

**Comment by SowjanyaMadala** [comment] 2020-05-11 15:14
No Luck.. still not working..
Could you please try placing the image to attached worksheet (top left corner)?
[1218.DM003.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4610433/1218.DM003.xlsx)

**Comment by JanKallman** [comment] 2020-05-12 06:42
I can't reproduce your issue. Are you ok with mailing me the template, so I get the correct image and settings?
Also, do you copy the worksheet to an existing workbook or a new one? If you are using an existing workbook with different theme settings you can get unexpected results.

**Comment by SowjanyaMadala** [comment] 2020-05-12 13:11
It renders reports from SSRS in Excel format and saves in shared folder using File.Create method. Then merges to new workbook from different report files.
it works If I open source file before merging and do small change (changed value 0 to 1 and didn't touched image). so, I can't say it is specific to image.
It is minor issue compared to image copying for now.  I will try to reproduce with sample template if possible and get back to you.
but please make sure to release this version "5.1.0.135-20200430-develop" ASAP so that we can continue.

**Comment by JanKallman** [comment] 2020-05-12 13:13
We'll release a new version in the coming days.

**Comment by SowjanyaMadala** [comment] 2020-05-12 13:34
Sounds good, Thank you!

**Comment by JanKallman** [comment] 2020-05-13 11:45
The new version is out now. Made some additional fixes. 
I'll close this issue now.
Feel free to re-open this issue or create a new issue if it does not work properly.

**Closed by JanKallman** 2020-05-13 11:45 UTC
Labels: bug
