### ISSUE TITLE
Not a Legal OleAut Date when using EPPLUS dll AutoFitColumns()

### ISSUE THREAD

**Issue by addy2021** [EPPlusSoftware/EPPlus#550] opened 2021-12-10 08:43 UTC
An EPPLUS function worksheet5.Cells.AutoFitColumns() is giving an error after data in already loaded in Workshet Object. Also cannot debug into the DLL operation to find out which Column\Cell is causng the error. Can anyone help?
**Error Details**
`  {"Not a legal OleAut date."}
  Data: {System.Collections.ListDictionaryInternal}
  HResult: -2146233066
  HelpLink: null
  IPForWatsonBuckets: 0x00007ffb811fccc7
  InnerException: null
  IsTransient: false
  Message: "Not a legal OleAut date."
  RemoteStackTrace: null
  Source: Evaluation timed out
  StackTrace: "   at System.DateTime.TicksToOADate(Int64 value)\r\n   at OfficeOpenXml.ExcelRangeBase.FormatValue(Object v, ExcelFormatTranslator nf, String format, String textFormat)\r\n   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)\r\n   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()\r\n   at RiskReport.RiskReportForm.generateRiskReportExcel(Int32 runLogID) in C:\\Users\\<>\\<>\\Work Folder\\<>\\AWS Versions\\<>\\<>\\RiskReport\\Form1.cs:line 1004"
 TargetSite: {Double TicksToOADate(Int64)}
  WatsonBuckets: null
  _HResult: -2146233066
  _className: null
  _data: {System.Collections.ListDictionaryInternal}
  _dynamicMethods: null
  _exceptionMethod: null
  _exceptionMethodString: null
  _helpURL: null
  _innerException: null
  _ipForWatsonBuckets: 0x00007ffb811fccc7
  _message: "Not a legal OleAut date."
  _remoteStackIndex: 0
  _remoteStackTraceString: null
  _safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
  _source: "mscorlib"
  _stackTrace: {sbyte[192]}
  _stackTraceString: null
  _watsonBuckets: null
  _xcode: -532462766
  _xptrs: 0x0000000000000000`

**Comment by JanKallman** [comment] 2021-12-13 06:42
Can you attach code to reproduce this and the workbook if nessecary.

**Comment by JanKallman** [comment] 2021-12-14 13:45
This is likely due to an oa-date larger thatn DateTime.MaxDate. I have added a fix for this in EPPlus 5.8.4

**Closed by JanKallman** 2021-12-14 13:45 UTC

**Comment by addy2021** [comment] 2021-12-16 07:33
Thanks @JanKallman & you're right i found that error was due to strange date(0002-10-29) in some of rows which 'AutoFitColumn' must be considering as Date larger than oa-date. I have done error handling for now.
