### ISSUE TITLE
Save() of package after adding PivotTable gives exception

### ISSUE THREAD

**Issue by EsbenRud** [EPPlusSoftware/EPPlus#232] opened 2020-11-17 12:46 UTC
Hi, after upgrading to EPPLus 5.4.1 I experienced an exception during Save() of package. I have now isolated the issue to something that has to do with creating PivotTables. I have uploaded a sample project that will throw the mentioned exception when you unpack and run the project.
Best regards
Esben Rud Nielsen, Bankdata
[ConsoleApp1.zip](https://github.com/EPPlusSoftware/EPPlus/files/5553509/ConsoleApp1.zip)

**Comment by JanKallman** [comment] 2020-11-17 13:11
I will have a look

**Comment by JanKallman** [comment] 2020-11-17 15:20
This should be fixed now. Feel free to verify it using our develop nuget feed...
https://ci.appveyor.com/nuget/epplus

**Comment by EsbenRud** [comment] 2020-11-17 16:40
Works great, thanks for quick helping.

**Comment by EsbenRud** [comment] 2020-11-18 09:11
By the way I tried to re-run the project after having applied your new version and saved the xlsx-file. Now I get nearly the same exception when I get the worksheet (see screenshot).
![image](https://user-images.githubusercontent.com/12291383/99509710-6b733180-2986-11eb-9406-79732752414c.png)

**Comment by JanKallman** [comment] 2020-11-18 09:13
I'll check

**Comment by JanKallman** [comment] 2020-11-18 09:54
I can't reproduce this. Can you attach text.xlsx?

**Comment by EsbenRud** [comment] 2020-11-18 10:48
The problem arrises when I try to Add a PageField (boolean) and then update it's Items to Hidden except for the "false" value. After that even Excel claims that there is an error in the file. I will upload the new ConsoleApp1.zip with test.xlsx included.
[ConsoleApp1.zip](https://github.com/EPPlusSoftware/EPPlus/files/5559468/ConsoleApp1.zip)

**Comment by JanKallman** [comment] 2020-11-18 13:34
Thanks for reporting this. When you delete the worksheet containing the pivot the it's not properly cleaned up, causing the workbook to be corrupt. Please not that the text.xlsx supplied in the sample is corrupt due to this.
I have commit a fix for this issue.

**Comment by EsbenRud** [comment] 2020-11-18 13:46
I have now tested it and it works great, Thanks

**Comment by JanKallman** [comment] 2020-11-18 13:48
Great, I'll try to release a new version tomorrow in nothing else shows up

**Comment by JanKallman** [comment] 2020-11-19 14:43
Fixed in version 5.4.2

**Closed by JanKallman** 2020-11-19 14:43 UTC
Labels: bug
