### ISSUE TITLE
After reading with EPPLUS, the image in the Excel file is deformed

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#1650] opened 2024-10-22 13:47 UTC
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.4.1

### Spreadsheet application

Excel365

### Description

I did nothing but load the file using EPPLUS and save it as a new file using saveas method. The picture elements in the file were deformed and the Placement attribute (VBA interface) of the picture changed from xlMoveAndSize to xlMove

![image](https://github.com/user-attachments/assets/b25c0a07-d8df-4e1e-962f-36908e83957e)
[picture deformed.xlsx](https://github.com/user-attachments/files/17477203/picture.deformed.xlsx)

**Comment by OssianEPPlus** [comment] 2024-10-22 15:06
Issue appears to be duplicate of #1626

Try our [NuGet Develop Feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed)

Fix for this was merged yesterday. It appears to work correctly when attempting to reproduce in develop

**Comment by minren118** [comment] 2024-10-22 15:09
I have just compiled with a develop7 branch and no longer have this problem, thank you for your efforts

**Closed as completed** 2024-10-23 06:55 UTC
Labels: bug
