### ISSUE TITLE
Inserting a row duplicates comments on that row

### ISSUE THREAD

**Issue by salihvs** [EPPlusSoftware/EPPlus#259] opened 2020-12-14 07:59 UTC
If there are comments on inserted row it should move comments according to the direction selection (eShiftTypeInsert enum). Now It copies comments to new direction but leaves the comments at the same cell too. It worked in older versions like 5.1.2

I'm using version 5.4.2 with .net standard 2.1

**Comment by JanKallman** [comment] 2020-12-14 10:06
I cant reproduce this. Can you provide a sample.

**Comment by JanKallman** [comment] 2021-03-15 13:06
We have fixed a few comments related bugs in EPPlus 5.6. Unsure if it helps. I will close this issue as I cant reproduce you problem.

**Closed by JanKallman** 2021-03-15 13:06 UTC
