### ISSUE TITLE
Crash when Notes are copied

### ISSUE THREAD

**Issue by R4cOOn** [EPPlusSoftware/EPPlus#552] opened 2021-12-13 14:55 UTC
Copying a line that contains a Note works fine.  
However, when the Excel file gets opened again there's a crash

``
System.ArgumentException: 'An item with the same key has already been added. Key: _x0000_s1025'
``

We used to use version 5.6.4 with .NET Core 5  
However it looks like there was an issue when we updated to .NET Core 6 and a lot of files were failing to calculate correctly and where erroring with `#Value!`  
Updating to 5.8.3 (latest) fixed that issue but brought the new one with the copied notes crashing the file loading.

Further testing shows that version 5.7.3 is the latest one where the note copying works.

[ExcelTesting.zip](https://github.com/EPPlusSoftware/EPPlus/files/7704633/ExcelTesting.zip)

**Comment by JanKallman** [comment] 2021-12-14 07:08
Thanks, I'll have a look at this.

**Comment by JanKallman** [comment] 2021-12-14 08:23
Id was overwritten when copying the comment causing a the copied comment to have the same Id.

**Comment by R4cOOn** [comment] 2021-12-14 08:33
Thanks for getting on this so quickly.

**Comment by JanKallman** [comment] 2021-12-14 13:43
This fix is included in EPPlus 5.8.4

**Comment by NikolayPetkovBG** [comment] 2022-01-17 10:04
@JanKallman if seems the issue is not resolved - attached a new file that is causing the same bug.

[ExcelTesting-17012022.zip](https://github.com/EPPlusSoftware/EPPlus/files/7880898/ExcelTesting-17012022.zip)

**Comment by JanKallman** [comment] 2022-01-19 08:44
The attached Book2.xlsx has duplicate spid attributes in the \xl\drawings\vmlDrawing1.vml file. Is it created with an EPPlus version prior to this bugfix?
```xml
<v:shape id="_x0000_s1051" type="#_x0000_t202" style='position:absolute;
  margin-left:111.6pt;margin-top:4.2pt;width:154.2pt;height:57pt;z-index:1;
  visibility:hidden' spid="_x0000_s1047" spid="_x0000_s1038" insetmode="auto"
  fillcolor="#ffffe1" o:insetmode="auto">

```
You will need to remove the duplicate attribute if you want to use this template (as the xml parser fails to load this as it's not valid xml). 
To do this: rename the book2.xlsx file *.zip. In the package, edit any \xl\drawings\*.vml files and remove the duplicate spid attributes.

**Comment by NikolayPetkovBG** [comment] 2022-01-19 08:47
@JanKallman thank you!

**Closed** 2022-02-07 14:21 UTC
Labels: bug
