### ISSUE TITLE
Using Themes 

### ISSUE THREAD

**Issue by rheophile10** [EPPlusSoftware/EPPlus#760] opened 2022-12-15 14:38 UTC
I am using themes manager to load themes files 

```
public class ThemeLoader
{
    public static void LoadThemeToClientFile(FileInfo themeFile, FileInfo outFile, FileInfo clientFile) 
    {
        var outputPackage = new ExcelPackage(clientFile);
        outputPackage.Workbook.ThemeManager.DeleteCurrentTheme();
        outputPackage.Workbook.ThemeManager.Load(themeFile);
        outputPackage.SaveAs(outFile);
    }
}
```

And the theme doesn't seem to take. The theme is a modern Office theme and the file is generated with python xlsxwriter (its a 2006-2010 .xlsx file) 

I have unzipped the file that comes out the other end of this and I see theme1.xml changes but when I open the file the styles in the cells are still the colours from the 2006-2010 office theme. When I load the theme file with the client I see that a lot of extra changes are made to the styles.xml (lots of new stylesheets brought in) and I notice of course when I ThemesManager.Load(themefile) no changes to styles.xml occur

Has anybody else run into this problem? What can we do? 

Let me know if you need any more sample code or problems to assist with this

**Comment by JanKallman** [comment] 2022-12-19 07:31
I am unsure what the issue is. Can you provide a test project describing your issue in detail.

**Comment by JanKallman** [comment] 2023-01-18 15:02
I'll close this as we can't reproduce the issue. Feel free to re-open if you can provide a test case.

**Closed by JanKallman** 2023-01-18 15:02 UTC
