### ISSUE TITLE
IFERROR function does not handle errors in nested functions

### ISSUE THREAD

**Issue by kemsky** [EPPlusSoftware/EPPlus#1102] opened 2023-10-13 19:46 UTC
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

MacOS

### Epplus version

6.2.10

### Description

The following code results in `#VALUE!`.

```charp
[Test]
public void Test()
{
    using (var excel = new ExcelPackage())
    {
        var worksheet = excel.AddSheet("Test Worksheet");
        var targetCell = worksheet.Cell(1,1);
        var validationCell = worksheet.Cell(1,2);

        validationCell.Formula = "IFERROR(SUBSTITUTE(RIGHT(A1,LEN(A1)-FIND(\"-\",A1)),\"-\",\"|\"),\"0\")";

        targetCell.SetText("invalid");

        validationCell.Calculate();

        var result = validationCell.GetValue<string>();

        Assert.AreEqual("0", result);
    }
}
```

**Comment by OssianEPPlus** [comment] 2023-10-16 05:59
Indeed this appears to be a bug I'm looking into it

**Comment by OssianEPPlus** [comment] 2023-10-16 06:24
The reason is an issue with our handling of the Substitute function. We are working on a fix. However the issue is already fixed in the epplus7 pre-release if you would like to try that.

**Closed as completed** 2023-10-17 07:14 UTC
Labels: bug
