### ISSUE TITLE
MSExcel error on Slicers

### ISSUE THREAD

**Issue by AntoonHzn** [EPPlusSoftware/EPPlus#291] opened 2021-02-01 10:26 UTC
Hello,
I have a pre-constructed excel file. Worksheet for data (initial empty), one for a few Slicers an timeline and a few for data resulst in a couple of pivot tables.
Programmaricly, using EPPLUS, if fill the data sheet and save the workbook back to disk.
Up untill version 5.1.2 there was no problem.
In your latest version, 5.5.2, i get an error when opening the new workboook in Excel. See att 1.
![Screenshot 2021-02-01 112035](https://user-images.githubusercontent.com/78351259/106445791-bda0fa80-647f-11eb-9def-f1fbbd4b5f34.jpg)
After accepting Repair all slicers are gone with the message in att 2.
![Screenshot 2021-02-01 112354](https://user-images.githubusercontent.com/78351259/106446033-0f498500-6480-11eb-8773-93746cc99bd2.jpg)
Is it possible i'm doing somthing wrong or could it be a bug?
Regards, Antoon

**Comment by JanKallman** [comment] 2021-02-02 07:52
Can you attach the workbook and some code to reproduce?

**Comment by JanKallman** [comment] 2021-02-24 08:59
I close this issue as I can't reproduce this. Feel free to reopen the issue with a reproducible test case

**Closed by JanKallman** 2021-02-24 08:59 UTC
