### ISSUE TITLE
After calling ExcelRange.Insert, other merged cells are not correct

### ISSUE THREAD

**Issue by darko2o8** [EPPlusSoftware/EPPlus#852] opened 2023-04-21 04:25 UTC
![image](https://user-images.githubusercontent.com/7909311/233540334-e6b631bd-ac1f-4922-b920-174e1300d2e9.png)
Call the method sheet.Cells["A2:C3"].Insert(eShiftTypeInsert.Right)
![image](https://user-images.githubusercontent.com/7909311/233540613-3bfb5818-d86d-419b-9d5b-e2c59f4f09b8.png)
A1 and A6 have also been shifted backwards

**Comment by OssianEPPlus** [comment] 2023-04-24 08:14
I'm unable to reproduce this issue in EPPlus 6.2.2 after setting up a similar sheet and running
 
`sheet.Cells["A2:C3"].Insert(eShiftTypeInsert.Right)`

it produces the following correct result
![bild](https://user-images.githubusercontent.com/122265629/233937717-b6efcd52-e1f1-424c-b0e0-426cf3466aa2.png)

would you mind sending us the before and after workbooks and a reproducible code sample?

**Comment by OssianEPPlus** [comment] 2023-04-24 14:39
Those workbooks appear to be broken links. We would need the actual files. I tried running the code provided and again was unable to reproduce the error so the problem should lie with the workbooks themselves.

Is the error consistent if you create a new file with the same data from scratch and run that code on it?

**Comment by OssianEPPlus** [comment] 2023-04-25 07:23
Good, thank you! We've been able to reproduce the issue and are investigating for a fix this does indeed seem to be a bug with merged cells.

**Closed** 2023-04-25 14:31 UTC
