### ISSUE TITLE
Formula Parsing Error: Unterminated String Exception for Formulas with Worksheet Names Containing Special Characters and Whole-Column References

### ISSUE THREAD

**Issue by chris-newsome** [EPPlusSoftware/EPPlus#1689] opened 2024-11-14 17:05 UTC
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.4.1

### Spreadsheet application

Excel

### Description

I'm encountering an Unterminated String exception when using formulas in EPPlus that reference worksheet names with special characters (e.g., #) and whole-column references (e.g., $D:$D). The formula =@INDEX('#AdjustmentISAccounts'!$D:$D,$S$5+ROW()-ROW($D$16)) consistently throws this error.

**Comment by OssianEPPlus** [comment] 2024-11-15 14:01
Since you appear to be using the `@` operator, please check [this page](https://github.com/EPPlusSoftware/EPPlus/wiki/Dynamic-arrayformulas) if you're using implicit intersection.

I am unable to reproduce your error both in the most recent version of Epplus and in 7.4.1. as using your formula results in a `#NAME?` error and an epplus acceptable version of the formula without the `=` or `@` operator appears to give expected results. After applying .Calculate to the cell holding the formula.

Please provide a reproducible code case and if possible a workbook wherein the error occurs. And if possible some part of the stacktrace.

When exactly is your exception happening?
Is it happening when epplus reads in a workbook? Is it happening when you assign this formula to a cell/range in epplus? Or some other scenario?

**Comment by chris-newsome** [comment] 2024-11-15 17:41
The workbook is generated server-side, and the exception occurs during the process of inserting rows into the worksheet. Specifically, this happens when the system attempts to insert rows while working with a formula. Here’s the relevant code snippet:

```
internal ExcelRangeBase GenerateRowsFromTemplate(ExcelWorksheet wks, ExcelRangeBase templateRow, int insertCount)
{
    if (insertCount <= 0)
    {
        return templateRow;
    }

    int originalTemplateRow = templateRow.Start.Row;

    wks.InsertRow(templateRow.Start.Row, insertCount, templateRow.Start.Row);

    // Grab templateRow again after inserting columns
    templateRow = templateRow.Offset(insertCount, 0);

    // Copy data from row template to newly inserted blank columns
    for (int j = 1; j <= insertCount; j++)
    {
        var sourceRange = wks.Cells[$"{templateRow.Start.Row}:{templateRow.End.Row}"];
        var destRange = wks.Cells[$"{templateRow.Start.Row - j}:{templateRow.End.Row - j}"];

        sourceRange.Copy(destRange);

    }

    return wks.Cells[$"{originalTemplateRow}:{originalTemplateRow + insertCount}"];
}
```

### Additional Details

1. **Exception Timing**: The exception happens during the InsertRow method call or when copying the data from the template row to the newly inserted rows using Copy.
2. **Formula Context**: The template rows contain formulas. I don't think the @ operator is getting inserted until the workbook is opened on the users machine. The default formula doesn't include the @ operator.
3. **Stack Trace**: Unfortunately, I currently do not have the full stack trace but can provide it if needed. However, the error message specifically mentions an "Unterminated string."

**Comment by OssianEPPlus** [comment] 2024-11-18 09:14
Thank you! We've been able to reproduce your error! And are working on a fix.

In the meantime if possible, avoid specifically '#' in worksheet names. There was an incorrect 'If' determining the worksheet to be a table reference because of that operator in the specific case of inserting rows,

**Closed as completed** 2024-11-18 14:50 UTC
Labels: bug

**Comment by chris-newsome** [comment] 2024-11-18 20:23
This is great. Thank you so much! Is there a new package version I can upgrade to for the fix?
