### ISSUE TITLE
VBA Module name exceeds 31 characters and corrupts workbook on open

### ISSUE THREAD

**Issue by chris-shelton** [EPPlusSoftware/EPPlus#485] opened 2021-09-13 16:33 UTC
We are having an issue where we take a worksheet, within a workbook that has a VBA project and code, and copy it. 

On the add sheet call within the copy method, it is copying the vba project info and trying to create a copy of the module. 

We calculate a new sheet name for the copy, which is typically the name of a real estate property, such as "1234 street name blvd CVS downtown". We make sure all characters are valid and reduce the name to 31 characters before passing it into the Worksheet.Copy method. 

In the "GetModuleNameFromWorkshee" method in ExcelVBAProject.cs, it checks for a "valid" name and if not, it uses a "sheet{x}" name. Our new sheet name is passing the test and getting set for the VBA module name. Somewhere however, if you look in the VBA Editor within excel, you can see the name "Worksheet" is prefixed to the already maxed out 31 character name for the VBA module. 

A workaround is to limit names to be 17 characters to allow for the "Worksheet" being prefixed. However this is not good as it does not allow enough space in the sheet name to be workable for us. 

I have submitted a PR #482 and I see why the test fails as we don't address a VBA module directly to insert code manually. We use a template with the VBA code already in the workbook for all workbook generation. 

I'm not sure what the final solution is here. We recently migrated from the latest 4.x. branch to the latest 5 version. It looks like on the 4 branch, the code to check a valid name was much different, which never caused an issue for us. 
Maybe the issue is somewhere else, but this is what we've reduced it to. 

The way we do the copy is we have a base sheet named something like "Real Estate Repeater" in the template we start with. We then dynamically copy that sheet X number of times for each property needed, and then hide the original Repeater sheet. If that helps with the scenario at all.

**Comment by JanKallman** [comment] 2021-09-14 06:42
Thanks for the detailed description. I will have a look at this and get back to you.

**Comment by JanKallman** [comment] 2021-09-20 08:36
The problem seems to be here,
https://github.com/EPPlusSoftware/EPPlus/blob/ae3e8a28ddcaeaeb9d71a6c5c20afd6577a861c8/src/EPPlus/Core/Worksheet/WorksheetCopyHelper.cs#L109
, where we set the name of the module on the copied worksheet instead of the newly added worksheet. I'll provide a fix for that. 
I'm unsure if this fixes the issue for you, so I'll do some more checks on this.
I'll have a look at the PR as well

**Comment by JanKallman** [comment] 2021-09-20 09:46
Can you verify if this fix solves your issue with our latest develop build?
https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by chris-shelton** [comment] 2021-09-20 15:21
Hey, just tried with the latest dev build, still had an issue. 
Here is a screenshot of the VBA Editor:
![image](https://user-images.githubusercontent.com/7957370/134028156-9818f423-7f51-4020-9d47-915049d1dff0.png)

You can see on the bottom few tabs, it adds a "Worksheet" prepended to the module name, which takes the already maxed out 31 character limit and makes it larger.

**Comment by JanKallman** [comment] 2021-09-21 06:34
The problem seems to happen when a worksheet name starts with a number. A modual name is not allowed to start with a number so it causes the error on load. I will provide a solution during the day.

**Comment by JanKallman** [comment] 2021-09-21 12:29
This should be fixed in version 5.7.5. The problem was when a worksheet name started with a number. The validation of the vba module name did validate this correctly. If you still have problems with version 5.7.5, please re-open this issue and provide a reproduceble sample.

**Closed by JanKallman** 2021-09-21 12:29 UTC
Labels: bug
