### ISSUE TITLE
Error when calling AutoFitColumns

### ISSUE THREAD

**Issue by lommez** [EPPlusSoftware/EPPlus#526] opened 2021-11-03 21:08 UTC
I got the follwing exception when calling AutoFitColumns

```
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
```
   
My application is running on Windows with .Net 5.0.
Is this a known error?

**Comment by JanKallman** [comment] 2021-11-04 07:50
No, I have not seen this before. Can you provide a reproducible  sample?

**Comment by JanKallman** [comment] 2021-11-24 07:05
I'll close this issue as I can't reproduce it. Feel free to re-open it with a reproducible sample?

**Closed by JanKallman** 2021-11-24 07:05 UTC
