### ISSUE TITLE
Cell data missing from 1 row

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#547] opened 2021-12-09 13:35 UTC
Hello,

With version 5.8.3, we have an issue where cell content from a single row is missing after reading with EPPlus.  We read an entire worksheet in which other rows have data, but just 1 row is read with empty content.  No error message occurs.  We found that simply opening and saving the Excel file resolves the issue for future reads.

I can't send an example since I would have to remove sensitive data first, and as such would save the file making the issue go away.  Is there maybe some part of the original file I can send that could give a clue to the issue?  Maybe [Content_Types].xml or .rels?  I noticed that after saving, Content_Types.xml and .rels have additional content and also a new directory "docProps" is added that wasn't there before.

Thanks,

Randall

**Comment by JanKallman** [comment] 2021-12-10 07:11
I can tell what's the issue by your description. Can you attach the workbook in our support portal or or mail it?

**Comment by rdhasse** [comment] 2021-12-10 18:19
Unfortunately, I cannot without an NDA in place.  The file contains sensitive financial data.  The issue goes away by simply saving the file so removing the data and saving doesn't help.

**Comment by JanKallman** [comment] 2021-12-13 07:48
I think we can arrange that if you want to. Open a case on our support portal and we can proceed from there.

**Comment by JanKallman** [comment] 2022-04-13 06:36
I'll close this issue as I cant reproduce the issue.

**Closed by JanKallman** 2022-04-13 06:36 UTC
