### ISSUE TITLE
Formatting with tables

### ISSUE THREAD

**Issue by LRSkylark** [EPPlusSoftware/EPPlus#1085] opened 2023-10-02 14:37 UTC
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

6.2.9

### Spreadsheet application

Excel

### Description

I am currently trying to insert new lines into a Excel Table. However I am having a couple issues with formatting of the Table afterwards.

Issue 1:- When opening up the Excel File it complains about "problem with some content". I am able to work around this problem, but to do this I need to insert a blank row below the table, expand the table then delete the blank row. I think this is being caused by the merged cells which are located below the table, but this is still causing problems

Issue 2:- Table Formatting is being partially removed, I have no idea what is causing this one or how to work around it. I have tried multiple things like saving the style then re applying it to it after extending the table amongst other thigns and I can not find a work around. See Figure 1 for the output, Figure 2 is what it should look like, as that is the table being modified from the source. I am using a custom Table Style.

`//Insert a row to prevent issues`
`sheet.InsertRow(table.Range.End.Row + 1, 1);`
`//Add rows to the table`
`table.AddRow(length);`
`//Delete the row to keep formatting correct`
`sheet.DeleteRow(table.Range.End.Row + 1, 1);`

![image](https://github.com/EPPlusSoftware/EPPlus/assets/146739609/ca66d7e7-282d-4968-9112-8ecd900838c0)
Figure 1:- Output File with the wrong formatting

![image](https://github.com/EPPlusSoftware/EPPlus/assets/146739609/c7591359-6001-47d2-80bc-022d3455d7bd)
Figure 2:- Expected Output File with the correct formatting

**Comment by LRSkylark** [comment] 2023-10-03 07:43
I have now got a work around, however it is not great, the cells which don't have the problems is consistent, D11 never has the problem, because of that I am taking the forammting of D11 and copying it to the other lines, this is obviously a work around and shouldn't need to be done mind. See the code below

`ExcelRangeBase source = sheet.Cells[11, 4, 11, 4];`
`ExcelRangeBase destination = table.Range;`
`source.CopyStyles(destination);`

**Comment by OssianEPPlus** [comment] 2023-10-03 07:50
I'm looking into this currently, thanks for the update!

Two notes of interest in the meantime: 
1. We released 6.2.10 yesterday. I don't _think_ it resolves this but I know there were some bugs resolved relating to rows. Might be worth testing. Currently setting up a test which I'll be running in both versions.
2. As a commercial customer you should have access to our [Priority Support](https://epplussoftware.com/en/Support) if you wish where excelfiles and support cases are handled privately so that e.g. workbooks can be uploaded without it being public.

**Comment by OssianEPPlus** [comment] 2023-10-03 08:35
I was unable to reproduce your issue.

I attempted creating an empty workbook, adding a custom table-style, adding a table with merged cells underneath and then testing both/either adding or deleting rows. All in 6.2.9 In both cases it functioned as expected. 

This along with what you describe in "Issue1" implies that some data has been corrupted/missplaced within the worksheet or workbook xml files themselves. You can confirm this via testing adding rows to a table with a custom style in a brand new worksheet.

In order to fully understand, reproduce and resolve your issue we will likely need the workbook itself and if possible a reproducible code example.

I'd recommend contacting your administration for log-in details to our support portal. Putting up a support ticket there wherein you upload the workbook.

**Closed as not planned** 2023-11-02 11:15 UTC
Labels: bug
