### ISSUE TITLE
Style.Fill.BackgroundColor.SetColor no longer seems to work

### ISSUE THREAD

**Issue by insomniac4104** [EPPlusSoftware/EPPlus#327] opened 2021-03-08 14:31 UTC
I am using the latest nuget package of Epplus with the latest visual studio update 16.9.0 on C# .net 4.7.2 framework and the fill background color proptery isn't working.  But the Style.Font.Color.SetColor(Color.Red) works fine.
Am I missing something with the syntax?

var cell = workSheet.Cells[row, 7];
cell.Style.Fill.PatternType = ExcelFillStyle.Solid;                                                    
 cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Red);

**Comment by JanKallman** [comment] 2021-03-09 09:51
Work fine when I try it (with row set to 1). Can you supply a full sample.

**Comment by JanKallman** [comment] 2021-03-15 14:29
I close this issue as I cant reproduce the issue. Feel free to re-open with a full test case.

**Closed by JanKallman** 2021-03-15 14:29 UTC
