### ISSUE TITLE
Formula NORMSINV returning #NAME?

### ISSUE THREAD

**Issue by Paul3816547290** [EPPlusSoftware/EPPlus#541] opened 2021-11-25 12:10 UTC
The worksheet I was performing a calculation on has some formulas like =NORMSINV(0.25) 
In excel this calculates to -0.67448975
If I call calculate on these cells within EPPlus the cell value returns #NAME? like the formula was unknown.

**Comment by Paul3816547290** [comment] 2021-11-25 18:47
I have also discovered that when an unknown formula is embedded like  =SUM(UNKNOWNFORMULA(0)) 
The #NAME? for UNKNOWNFORMULA in excel would roll up and the =SUM() would also emit #NAME?  in EPP it does not and SUM simply continues to evaluate as some other result hiding the error.

**Comment by swmal** [comment] 2021-11-26 11:29
Hi,
the NORMSINV function is not supported in EPPlus, see this list of supported functions: https://github.com/EPPlusSoftware/EPPlus/wiki/Supported-Functions
I'll have a look at the handling of errors in the SUM function, intended behaviour is that execution should be interupted and the error returned unless the function has parameters to ignore errors.

**Comment by swmal** [comment] 2021-11-30 11:39
This has been fixed in the develop branch, you can test it via our development nuget feed if you like: https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

We have also added support for 6 new normal distribution functions including NORMSINV. The fix and the new functions will be included in the next version.

**Closed** 2022-01-14 11:16 UTC
Labels: enhancement
